### ISSUE TITLE
Dependencies added conditionally are incompatible with core locking

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-nebula-integration#19]
We've been working around IntelliJ's wonky handling of `providedCompile`/`providedRuntime` by conditionally moving it to provided only when tasks are requested (as is the case when fetching models over the tooling API).

However, that causes core locking to fail when importing into the IDE. We consider that an IntelliJ bug, however we don't have alternative for these provided dependencies and will hamper core locking adoption:

https://youtrack.jetbrains.com/issue/IDEA-197475

**Comment by ljacomet** [comment]
Similar Gradle issue: gradle/gradle#5639

**Comment by ljacomet** [comment]
Now that #15 is resolved, this should be less of an issue and probably work as-is.

Please comment if that is not the case.

**Comment by chali** [comment]
I tested this and I think the experience is still not great. Here is what I tried.

I began with this project and lock generated via `./gradlew dependencies --write-locks`
```
apply plugin: 'java'
apply plugin: 'war'

repositories {
    mavenCentral()
}

dependencyLocking {
    lockAllConfigurations()
}

dependencies {
    compile 'junit:junit:4.12'

    if (!gradle.startParameter.taskRequests.isEmpty()) {
        providedRuntime 'org.slf4j:slf4j-api:1.8.0-beta2'
    }
}
```
Sync in Intellij had this output:
```
CONFIGURE SUCCESSFUL in 0s
Dependency lock state for configuration 'runtimeClasspath' is out of date: Did not resolve 'org.slf4j:slf4j-api:1.8.0-beta2' which is part of the lock state
```
But imported dependencies in the IDE were not updated so any change in build file was not reflected in the IDE. I had to remove if condition to be able to do that.

**Comment by chali** [comment]
I was expecting what you did in the video :-) I found that I had a wrong Gradle version. My bad. I'm sorry about the confusion. With the right version, it is doing what I saw in your video.

**Comment by ljacomet** [comment]
No worry, better to clear up confusion than having a defect to handle 😉
